import type { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms and conditions for using the Toodls application.",
};

const EFFECTIVE_DATE = "July 1, 2026";

export default function TermsOfServicePage() {
  return (
    <LegalLayout title="Terms of Service" effectiveDate={EFFECTIVE_DATE}>
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to
        and use of the Toodls mobile application (the &ldquo;App&rdquo;)
        provided by Toodls (&ldquo;Toodls,&rdquo; &ldquo;we,&rdquo;
        &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By downloading, accessing,
        or using the App, you agree to be bound by these Terms. If you do
        not agree, do not use the App.
      </p>

      <h2>1. Using Toodls</h2>
      <p>
        Toodls lets you scan items using your device&apos;s camera to
        receive AI-generated identification, condition assessment, and
        pricing estimates, and to organize items into folders and export
        listings. You must be at least 13 years old to use the App and
        must provide accurate information when creating an account.
      </p>

      <h2>2. Estimates Are Not Guarantees</h2>
      <p>
        Item identification, condition ratings, resale value estimates,
        and suggested pricing are generated by automated tools and are
        provided for informational purposes only. Toodls does not
        guarantee the accuracy of any estimate, and actual resale value
        may differ. You are solely responsible for any decision to keep,
        sell, or donate an item, and for any price you set or transaction
        you complete.
      </p>

      <h2>3. Your Content</h2>
      <p>
        You retain ownership of the photos and content you upload to the
        App (&ldquo;Your Content&rdquo;). By using the App, you grant
        Toodls a limited, worldwide license to host, process, and display
        Your Content solely to provide and improve the App&apos;s
        features, such as generating listings and exports. You are
        responsible for ensuring you have the right to upload and use Your
        Content.
      </p>

      <h2>4. Marketplace and Third-Party Sales</h2>
      <p>
        Toodls helps you prepare and export listings but is not a
        marketplace, buyer, seller, or party to any transaction between
        you and a third party. Any sale, donation, or exchange you conduct
        using listings or exports generated by Toodls is solely between
        you and the other party, and Toodls is not responsible for the
        outcome of those transactions.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the App for any unlawful purpose or to scan items you do not own or have rights to sell.</li>
        <li>Attempt to reverse-engineer, disrupt, or gain unauthorized access to the App or its systems.</li>
        <li>Upload content that is infringing, misleading, or violates the rights of others.</li>
        <li>Use automated means to access or scrape the App beyond normal use.</li>
      </ul>

      <h2>6. Subscriptions and Purchases</h2>
      <p>
        Certain features of the App may require a paid subscription or
        one-time purchase. Prices, billing terms, and cancellation
        policies will be presented at the time of purchase and are also
        governed by the terms of the app store through which you made the
        purchase (such as the Apple App Store).
      </p>

      <h2>7. Intellectual Property</h2>
      <p>
        The App, including its design, features, and underlying
        technology, is owned by Toodls and protected by intellectual
        property laws. These Terms do not grant you any rights to
        Toodls&apos; trademarks, logos, or branding.
      </p>

      <h2>8. Disclaimer of Warranties</h2>
      <p>
        The App is provided &ldquo;as is&rdquo; and &ldquo;as
        available&rdquo; without warranties of any kind, whether express
        or implied, including warranties of merchantability, fitness for a
        particular purpose, or non-infringement. We do not warrant that
        the App will be uninterrupted, error-free, or that any estimate
        will be accurate.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Toodls will not be liable
        for any indirect, incidental, special, consequential, or punitive
        damages, or any loss of profits or revenues, arising from your use
        of the App or reliance on any estimate, recommendation, or
        listing generated through it.
      </p>

      <h2>10. Termination</h2>
      <p>
        We may suspend or terminate your access to the App at any time if
        we believe you have violated these Terms. You may stop using the
        App and delete your account at any time.
      </p>

      <h2>11. Dispute Resolution and Binding Arbitration</h2>
      <p>
        <strong>
          Please read this section carefully. It affects your legal rights,
          including your right to file a lawsuit in court and to have a jury
          trial.
        </strong>
      </p>
      <p>
        <strong>Agreement to arbitrate.</strong> You and Toodls agree that
        any dispute, claim, or controversy arising out of or relating to
        these Terms or the App will be resolved by final and binding
        arbitration on an individual basis, rather than in court, except as
        set out below. This includes, without limitation, any dispute
        relating to the App&apos;s use of artificial intelligence &mdash; such
        as AI-generated item identification, condition assessments, resale
        value or pricing estimates, generated listings, exports, or any
        output, error, or outcome produced by the App&apos;s automated or
        AI-driven features.
      </p>
      <p>
        <strong>AI outputs are estimates.</strong> You acknowledge that
        AI-generated results are estimates and suggestions that may be
        inaccurate or incomplete, and you agree that any claim based on
        reliance on such output is subject to this arbitration provision and
        to the disclaimers and limitations in Sections 2, 8, and 9.
      </p>
      <p>
        <strong>Class action waiver.</strong> You and Toodls agree that each
        may bring claims against the other only in your or its individual
        capacity, and not as a plaintiff or class member in any purported
        class, collective, consolidated, or representative proceeding. The
        arbitrator may not consolidate more than one person&apos;s claims or
        preside over any form of class or representative proceeding.
      </p>
      <p>
        <strong>Arbitration process.</strong> The arbitration will be
        administered by the American Arbitration Association (AAA) under its
        then-current rules, and may be conducted in person, by documents, by
        phone, or online. The arbitration will take place in Mecklenburg County,
        North Carolina, or another mutually agreed location, and will be
        governed by the Federal Arbitration Act. The
        arbitrator&apos;s decision will be final and binding and may be
        entered as a judgment in any court of competent jurisdiction.
      </p>
      <p>
        <strong>Exceptions.</strong> Either party may bring an individual
        claim in small-claims court, and either party may seek injunctive or
        equitable relief in court to protect its intellectual property or
        confidential information. Nothing in this section prevents you from
        reporting a concern to a government agency.
      </p>
      <p>
        <strong>30-day right to opt out.</strong> You may opt out of this
        arbitration agreement by sending written notice to{" "}
        <a href="mailto:contact@toodls.app">contact@toodls.app</a> within 30
        days of first accepting these Terms. Your notice must include your
        name and the email associated with your account. If you opt out,
        neither you nor Toodls will be bound by this arbitration provision.
      </p>
      <p>
        <strong>Governing law.</strong> These Terms and any dispute between
        you and Toodls will be governed by the laws of the State of North
        Carolina, without regard to its conflict-of-laws rules, except that
        the Federal Arbitration Act governs the
        interpretation and enforcement of the arbitration provision above.
      </p>

      <h2>12. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the
        App after changes take effect constitutes your acceptance of the
        revised Terms.
      </p>

      <h2>13. Contact Us</h2>
      <p>
        If you have questions about these Terms, contact us at{" "}
        <a href="mailto:contact@toodls.app">contact@toodls.app</a>.
      </p>
    </LegalLayout>
  );
}
