import type { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms and conditions for using the Toodls application.",
};

const EFFECTIVE_DATE = "July 1, 2026";

export default function TermsOfServicePage() {
  return (
    <LegalLayout title="Terms of Service" effectiveDate={EFFECTIVE_DATE}>
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to
        and use of the Toodls mobile application (the &ldquo;App&rdquo;)
        provided by Toodls (&ldquo;Toodls,&rdquo; &ldquo;we,&rdquo;
        &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By downloading, accessing,
        or using the App, you agree to be bound by these Terms. If you do
        not agree, do not use the App.
      </p>

      <h2>1. Using Toodls</h2>
      <p>
        Toodls lets you scan items using your device&apos;s camera to
        receive AI-generated identification, condition assessment, and
        pricing estimates, and to organize items into folders and export
        listings. You must be at least 13 years old to use the App and
        must provide accurate information when creating an account.
      </p>

      <h2>2. Estimates Are Not Guarantees</h2>
      <p>
        Item identification, condition ratings, resale value estimates,
        and suggested pricing are generated by automated tools and are
        provided for informational purposes only. Toodls does not
        guarantee the accuracy of any estimate, and actual resale value
        may differ. You are solely responsible for any decision to keep,
        sell, or donate an item, and for any price you set or transaction
        you complete.
      </p>

      <h2>3. Your Content</h2>
      <p>
        You retain ownership of the photos and content you upload to the
        App (&ldquo;Your Content&rdquo;). By using the App, you grant
        Toodls a limited, worldwide license to host, process, and display
        Your Content solely to provide and improve the App&apos;s
        features, such as generating listings and exports. You are
        responsible for ensuring you have the right to upload and use Your
        Content.
      </p>

      <h2>4. Marketplace and Third-Party Sales</h2>
      <p>
        Toodls helps you prepare and export listings but is not a
        marketplace, buyer, seller, or party to any transaction between
        you and a third party. Any sale, donation, or exchange you conduct
        using listings or exports generated by Toodls is solely between
        you and the other party, and Toodls is not responsible for the
        outcome of those transactions.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the App for any unlawful purpose or to scan items you do not own or have rights to sell.</li>
        <li>Attempt to reverse-engineer, disrupt, or gain unauthorized access to the App or its systems.</li>
        <li>Upload content that is infringing, misleading, or violates the rights of others.</li>
        <li>Use automated means to access or scrape the App beyond normal use.</li>
      </ul>

      <h2>6. Subscriptions and Purchases</h2>
      <p>
        Certain features of the App may require a paid subscription or
        one-time purchase. Prices, billing terms, and cancellation
        policies will be presented at the time of purchase and are also
        governed by the terms of the app store through which you made the
        purchase (such as the Apple App Store).
      </p>

      <h2>7. Intellectual Property</h2>
      <p>
        The App, including its design, features, and underlying
        technology, is owned by Toodls and protected by intellectual
        property laws. These Terms do not grant you any rights to
        Toodls&apos; trademarks, logos, or branding.
      </p>

      <h2>8. Disclaimer of Warranties</h2>
      <p>
        The App is provided &ldquo;as is&rdquo; and &ldquo;as
        available&rdquo; without warranties of any kind, whether express
        or implied, including warranties of merchantability, fitness for a
        particular purpose, or non-infringement. We do not warrant that
        the App will be uninterrupted, error-free, or that any estimate
        will be accurate.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Toodls will not be liable
        for any indirect, incidental, special, consequential, or punitive
        damages, or any loss of profits or revenues, arising from your use
        of the App or reliance on any estimate, recommendation, or
        listing generated through it.
      </p>

      <h2>10. Termination</h2>
      <p>
        We may suspend or terminate your access to the App at any time if
        we believe you have violated these Terms. You may stop using the
        App and delete your account at any time.
      </p>

      <h2>11. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the
        App after changes take effect constitutes your acceptance of the
        revised Terms.
      </p>

      <h2>12. Contact Us</h2>
      <p>
        If you have questions about these Terms, contact us at{" "}
        <a href="mailto:support@toodls.app">support@toodls.app</a>.
      </p>
    </LegalLayout>
  );
}
